### ISSUE TITLE
Editing .dex files

### ISSUE THREAD

**Issue by JCWasmx86** [apk-editor/APK-Explorer-Editor#1]
Using [apktool](https://ibotpeaches.github.io/Apktool/) (Apache License 2.0), you can decompile an .apk file. (`apktool d`)
While the .apk file is decompiled, the classes.dex is converted to smali and the resources are extracted.
After making the changes to e.g. the smali files, the apk can be assembled (`apktool b`).

This tool could be integrated into the app, as it would give the app even more abilities.

**Comment by apk-editor** [comment]
@JCWasmx86 
I know that. However, I really don't want to integrate APKTools simply as a java lib (it's bit heavy too). I'm trying to learn more about it and eventually adapt it's core functionalities without bloating the app much. Will take more time. Thanks, anyway, for the comment.

**Comment by apk-editor** [comment]
@JCWasmx86 
Tis feature should be available from next release (F-Droid/GitHub versions 0.17 only). So, closing this issue. Feel free to re-open it if you're not satisfied.
