### ISSUE TITLE
Texts of version and size overlap with each other

### ISSUE THREAD

**Issue by yuhuitech** [apk-editor/APK-Explorer-Editor#10]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the main page, **texts of version and size overlap with each other**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.17, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope the texts are separated in this situation.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app, and wait until the loading progress is done
3.this error could be seen

**Screenshot**

(The overlap is marked in red)

<img src="https://user-images.githubusercontent.com/25502419/129735771-4ab2ae06-3ecd-4d7d-a34f-44416da99e5a.png" alt="copy" width="250"/>

**Environment**

1. Version of APK Explorer & Editor : 0.17
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by apk-editor** [comment]
@yuhuitech 
Thanks a lot for raising this issue and related PR. I'll merge it after some testing.
Have a great day.

**Comment by apk-editor** [comment]
@yuhuitech Closing this issue since youe PR is already merged. Thank You.
