### ISSUE TITLE
Exporting/Editing AndroidManifest.xml results in a broken file

### ISSUE THREAD

**Issue by yephny** [apk-editor/APK-Explorer-Editor#13]
Viewing AndroidManifest.xml is fine within the app, though you start to see strange characters and not a line-by-line organized xml file when you either edit the file within the app or export it.

**Comment by apk-editor** [comment]
@yephny 
This issue could be fixed as of c259f6b497159819b8a194556cab855c9f11dbd5, which is included with [v0.25](https://github.com/apk-editor/APK-Explorer-Editor/releases/tag/v0.25). So, closing this issue. But, feel free to reopen it, if you feel otherwise.
