### ISSUE TITLE
Export paths option are disabled in settings

### ISSUE THREAD

**Issue by user8446** [apk-editor/APK-Explorer-Editor#18]
Hi,

Both of the export path settings (APK & non-APK) are lined through and disabled. 

Exports do work as expected. They just default to \Android\data\com.apk.editor\files

What would cause the path settings to be disabled? Storage permission is on.

**Comment by apk-editor** [comment]
@user8446 
If you are on a newer Android version (API >= 29), app can't really write on most part of external storage (thanks to google).

**Comment by user8446** [comment]
I'm not an Android dev but since I am on the F-Droid version is there a way for the app to target a lower API as a workaround? My file manager ( https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/ ) does have access.

**Comment by apk-editor** [comment]
yes, but only the developer can do it. And, not advisable.
By the way, if you long click an exported app from APK's page, it will show you an option to save it into Download folder.

**Comment by user8446** [comment]
Ok would [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) be a better way?

**Comment by user8446** [comment]
I'm closing this since saving to the download folder would accomplish the same thing. Thank you for the developement
