### ISSUE TITLE
APK can't select 

### ISSUE THREAD

**Issue by skelletR** [apk-editor/APK-Explorer-Editor#23]
I have Xiaomi Poco X3 NFC android 10, when I go to select a apk say that (see picture) but on my Sony Xperia Z5 android 7.1.1 the apk can select the same apk file is not split, why ?
![IMG_20220725_192917](https://user-images.githubusercontent.com/25982450/180828991-b744583c-23d6-41dc-83ae-dec38283c077.jpg)

**Comment by apk-editor** [comment]
@skelletR 
Such issues usually happens when app failed to acquire the details of files from external file manager. Have you tried after installing a different file manager (say, Material Files)? Thanks

**Comment by skelletR** [comment]
> @skelletR Such issues usually happens when app failed to acquire the details of files from external file manager. Have you tried after installing a different file manager (say, Material Files)? Thanks

Yeah I try it with Material Files and works, I try it and with another but not work, thanks
