### ISSUE TITLE
Activity memory leak caused by the anonymous thread and invalid interrupt check

### ISSUE THREAD

**Issue by cuixiaoyiyi** [apk-editor/APK-Explorer-Editor#29]
An anonymous inner class will hold a reference to the this pointer of the outer class and will not be released until the thread ends.

It will hold the Activity and prevent its timely release.

com.apk.editor.activities.InstallerActivity

The anonymous thread can be replaced by static class to eliminate unnecessary references.

Besides,  an anonymous thread cannot call the interrupt() method until the Activity exits, so calling isInterrupted() in the thread of the [InstallerActivity ](https://github.com/apk-editor/APK-Explorer-Editor/blob/master/app/src/main/java/com/apk/editor/activities/InstallerActivity.java)refreshStatus() method may not always work.

The anonymous thread can be replaced by static class to eliminate unnecessary references and taken as a field to interrupt the thread.

If you agree, a PR will be submitted.

**Comment by apk-editor** [comment]
@cuixiaoyiyi 
Thank You, and please go ahead with the PR. I'll be happy to receive contributions from the community.
Have a nice day
Sunil

**Comment by apk-editor** [comment]
@cuixiaoyiyi 
Closing this issue as it is already addressed. Thank you.
