### ISSUE TITLE
Fix settings not displaying their updated values immediately

### ISSUE THREAD

**Issue by Nik-Kot** [apk-editor/APK-Explorer-Editor#34]
While working on adding jadx, I found this bug, caused by getData() regenerating the settings list instead of fetching a stored one that was previosly created.  Here's my fix:
https://github.com/Nik-Kot/APK-Explorer-Editor/commit/6726f9d5ea6a7a6ed0a3fd60edbcf35ca0c06c4b

**Comment by Nik-Kot** [comment]
This fix caused inconsistent behavoir when changing app language from settings, here is an updated one which adresses this issue: https://github.com/Nik-Kot/APK-Explorer-Editor/commit/6f435363275092242b3e601c60fa885b85edba46

**Comment by Nik-Kot** [comment]
Also changing theme won't update the displayed value because sThemeUtils do not adress this.

**Comment by Nik-Kot** [comment]
And also this: https://github.com/Nik-Kot/APK-Explorer-Editor/commit/955925b61ac4503d263fbbae85afb5c7f548d72e

RecyclerView reuses views and viewholders (as it's name implies), so you need to change back the values you updated for some items in the list.

**Comment by apk-editor** [comment]
@Nik-Kot 
I hope this issue is addressed (except a few cases) with 16470f370e4614ff7998c1cf6aac68cec8075c05
So, closing this. Thank you.
