### ISSUE TITLE
Portuguese short_description is too long

### ISSUE THREAD

**Issue by IzzySoft** [apk-editor/APK-Explorer-Editor#35]
Fastlane's `short_description.txt` is limited to 80 chars. Yours for `pt-BR` currently has 86 chars and thus will be truncated in the middle of its last word. Could you please fix that? I don't speak Portuguese, so I cannot vouch for correctness – but as it's clear it's an Android app, maybe it can simply be shortened to

> Instalador/explorador/editor de APKs/Pacote de apps de software livre

Done that locally in my repo now; would be nice if you could fix it here as well before the next release is tagged and "unfixes" it again with your listing :wink: Thanks in advance!

**Comment by apk-editor** [comment]
@IzzySoft 
Thanks, & I'll try to get the help from some pt-rBr users to solve this.

**Comment by apk-editor** [comment]
> @IzzySoft Thanks, & I'll try to get the help from some pt-rBr users to solve this.

Yes, please do it.
