### ISSUE TITLE
xapk or bundle export not working

### ISSUE THREAD

**Issue by fractalf** [apk-editor/APK-Explorer-Editor#41]
Hi!

I tried to export some apps from my phone. All apk-s were working, but the bundles just wouldn't "Save to Downloads"

Is this known behavier?

**Comment by apk-editor** [comment]
@fractalf 
Which version are you on? I believed that issue is fixed as of v0.25.

**Comment by fractalf** [comment]
Ah, that explains it...
I guess I'll install from releases here on github instead..

https://f-droid.org/en/packages/com.apk.editor/

![image](https://user-images.githubusercontent.com/5707457/217760864-cfac571a-540a-4250-9c02-57843bf05577.png)
