### ISSUE TITLE
please , min_sdk 21 (android 5.0) !

### ISSUE THREAD

**Issue by DI555** [apk-editor/APK-Explorer-Editor#5]
thank you for so usefull application!

please, come up AEE to min_sdk 21 (android 5.0) !
(or , if not possible, then at least to min_sdk 22, Android 5.1)
many thanks in advance!

**Comment by apk-editor** [comment]
@DI555 
I'm sorry, bit I afraid it will be a big headache which may not be worth to take by considering the less number of users still using those lower version.
