### ISSUE TITLE
Editing text files within AEE?

### ISSUE THREAD

**Issue by plsfixbusyboxforlatestandroid** [apk-editor/APK-Explorer-Editor#6]
Seriously, Thanks for creating this App It works amazingly well and has saved me tons of time.

Would it be possible to edit text files within AEE? It's a bit clunky to export, edit externally and then replace.

(I'm Currently on v0.14 from F-Droid, If this has already been implemented please ignore this issue.)

**Comment by apk-editor** [comment]
> Seriously, Thanks for creating this App It works amazingly well and has saved me tons of time.
> 
> Would it be possible to edit text files within AEE? It's a bit clunky to export, edit externally and then replace.
> 
> (I'm Currently on v0.14 from F-Droid, If this has already been implemented please ignore this issue.)

Hi,
Sorry for the delayed response. Infact, you can already edit text files using AEE. However, that editing asset files are too buggy and most likely make the newly created app corrupted (hence, disabled by default in the settings menu).

**Comment by deoxal** [comment]
I just want to change a false to a true in AndroidManifest.xml but I can't edit any files.

My keyboard is working fine since the search bar at the top lets me enter text.

**Comment by deoxal** [comment]
Okay just found that editing has to be enabled in the settings but using it means I don't get the parsed version anymore. Seeing a bunch of question marks in a white square in some parts doesn't help me.

**Comment by apk-editor** [comment]
@deoxal 
Editing text files are now fixed as of [v0.25](https://github.com/apk-editor/APK-Explorer-Editor/releases/tag/v0.25). Of course. there might still be issues when dealing with big APK's. Anyway, closing this issue. But, feel free to reopen it if you think the issue still exist. Thanks
