### ISSUE TITLE
Greek Translation 

### ISSUE THREAD

**Issue by VisionR1** [apk-editor/APK-Explorer-Editor#70]
Hi i almost finished greek translation for your app, now i checked it and correct some grammars etc.
When i finish, uploaded here ?

**Comment by apk-editor** [comment]
> Hi i almost finished greek translation for your app, now i checked it and correct some grammars etc. When i finish, uploaded here ?

Of course, or send me by email (whichever is convenient for you) to: apkeditor@protonmail.com. Thank you and sorry for the delayed response.

**Comment by VisionR1** [comment]
> > Hi i almost finished greek translation for your app, now i checked it and correct some grammars etc. When i finish, uploaded here ?
> 
> Of course, or send me by email (whichever is convenient for you) to: [apkeditor@protonmail.com](mailto:apkeditor@protonmail.com). Thank you and sorry for the delayed response.

It's ok, me too i'm little back, but in next week, I will have finished it and send it

**Comment by VisionR1** [comment]
> > Hi i almost finished greek translation for your app, now i checked it and correct some grammars etc. When i finish, uploaded here ?
> 
> Of course, or send me by email (whichever is convenient for you) to: [apkeditor@protonmail.com](mailto:apkeditor@protonmail.com). Thank you and sorry for the delayed response.

Here the greek translation. 
[APK Explorer.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/14542569/APK.Explorer.zip)

i have download the strings from the GitHub you write in description of the app in Google Play

And as a bonus here Greek translation for your other app aShell. 
[aShell.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/14542572/aShell.zip)

**Comment by VisionR1** [comment]
[Translator.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/14546863/Translator.zip)

**Comment by VisionR1** [comment]
Hi @apk-editor
Any news about the translation i had make you ?

**Comment by apk-editor** [comment]
@VisionR1 
I am sorry for the delay. I am really thankful for your contribitions. I will pick them without much delay (one by one, first for this app). Would you like to have a test build for this app? Please feel free to join our telegram group: https://t.me/apkexplorer

**Comment by VisionR1** [comment]
> @VisionR1 I am sorry for the delay. I am really thankful for your contribitions. I will pick them without much delay (one by one, first for this app). Would you like to have a test build for this app? Please feel free to join our telegram group: https://t.me/apkexplorer

Thanks you, yeah I would like to have a test build for this app

**Comment by apk-editor** [comment]
> > @VisionR1 I am sorry for the delay. I am really thankful for your contribitions. I will pick them without much delay (one by one, first for this app). Would you like to have a test build for this app? Please feel free to join our telegram group: https://t.me/apkexplorer
> 
> Thanks you, yeah I would like to have a test build for this app

Please get it from my [dropbox](https://www.dropbox.com/scl/fi/93b49dt15gud77y7vm0km/app-full-release-unsigned.apk?rlkey=nx6d0k8febf2pjkyzfbuewk2e&dl=0). It is an unsigned build. So, please use resign and install feature of this app.

**Comment by VisionR1** [comment]
> > > @VisionR1 I am sorry for the delay. I am really thankful for your contribitions. I will pick them without much delay (one by one, first for this app). Would you like to have a test build for this app? Please feel free to join our telegram group: https://t.me/apkexplorer
> > 
> > 
> > Thanks you, yeah I would like to have a test build for this app
> 
> Please get it from my [dropbox](https://www.dropbox.com/scl/fi/93b49dt15gud77y7vm0km/app-full-release-unsigned.apk?rlkey=nx6d0k8febf2pjkyzfbuewk2e&dl=0). It is an unsigned build. So, please use resign and install feature of this app.

As i see all look good with Greek Translation, only this remain untranslated because I did not see it inside in the string to translate

![1](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/ac3f8ea3-ae55-457d-ba72-ae6002b2a1db)
![2](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/f743dc58-5b39-43f3-a90f-d4dd6b98652b)
![3](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/9281a388-3795-4fac-ad36-9684bd6130b9)
![4](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/da1f8360-5d7c-47d1-a6b2-35c40ea4ad65)
![5](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/72bd96d4-a0dd-403a-be26-34233b53961a)

**Comment by VisionR1** [comment]
I see this line remain white, not like the others the word string=green and word name=blue

![6](https://github.com/apk-editor/APK-Explorer-Editor/assets/25982450/8c0de825-810b-4c93-a421-bef4033bd5a9)

**Comment by apk-editor** [comment]
@VisionR1 
Thanks. I will look on the issue in string.xml line#164.
Regarding the missing lines: they are included in either this [file](https://github.com/apk-editor/APK-Explorer-Editor/blob/master/app/src/full/res/values/strings.xml) (applicable only for F-Droid version) or in sCommon ([GitHub](https://github.com/sunilpaulmathew/sCommon), [POEditor](https://poeditor.com/join/project?hash=9AiLut8Dmy)) - a library used in most majority of my apps.

**Comment by VisionR1** [comment]
> @VisionR1 Thanks. I will look on the issue in string.xml line#164. Regarding the missing lines: they are included in either this [file](https://github.com/apk-editor/APK-Explorer-Editor/blob/master/app/src/full/res/values/strings.xml) (applicable only for F-Droid version) or in sCommon ([GitHub](https://github.com/sunilpaulmathew/sCommon), [POEditor](https://poeditor.com/join/project?hash=9AiLut8Dmy)) - a library used in most majority of my apps.

Oh now i see it, thanks you, go to translation and send you back
