### ISSUE TITLE
Slow file browser

### ISSUE THREAD

**Issue by linsui** [apk-editor/APK-Explorer-Editor#8]
It's extremly slow when browsing file system. Could you please use the native DocumentProvider instead? Thanks!

**Comment by apk-editor** [comment]
> It's extremly slow when browsing file system. Could you please use the native DocumentProvider instead? Thanks!

I don't know it is really possible by considering the fact that we often have to pick multiple files for split apk installation. Btw, the in-built file picker works reasonable good here unless the directory has too much files.

**Comment by linsui** [comment]
I guess you can pick files one by one. It's so slow for me that the app frozen every time.

**Comment by apk-editor** [comment]
> I guess you can pick files one by one. It's so slow for me that the app frozen every time.

I really don't think it's possible. Also, there will be some other reasons for app freezing in your case.

**Comment by apk-editor** [comment]
@linsui 
Closing this issue as it is already addresses (at least on newer android versions).
