### ISSUE TITLE
Some resigned apks are invalid

### ISSUE THREAD

**Issue by linsui** [apk-editor/APK-Explorer-Editor#9]
E.g. https://f-droid.org/repo/com.cosmos.unreddit_5.apk

**Comment by apk-editor** [comment]
@linsui 
I just downloaded the attached APK and installed using the "Resign and Install" option in my app. It installed fine. I don't know where exactly the problem in your case. I'm using Android 10. What about your case?

**Comment by linsui** [comment]
I'm using Android 11. The resigned apk can't be parsed.
[com.cosmos.unreddit_aee-signed.apk.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/6960753/com.cosmos.unreddit_aee-signed.apk.zip)

**Comment by apk-editor** [comment]
> I'm using Android 11. The resigned apk can't be parsed.
> [com.cosmos.unreddit_aee-signed.apk.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/6960753/com.cosmos.unreddit_aee-signed.apk.zip)

Just to narrow down the issue,  have you tried installing APK after using the "Resign only" option? If not, please try it and let me know if it is working. Anyway, I'll try to reproduce the issue on an Android 11 emulator (my phone is still running Android 10).

**Comment by linsui** [comment]
I can't install it. Android says it can't parse the package.

**Comment by sunilpaulmathew** [comment]
> I can't install it. Android says it can't parse the package.

Can you send me the signed APK, please. It should be in /sdcard/AEE/ (after using "Resign only" option). Thank You.

**Comment by apk-editor** [comment]
> I can't install it. Android says it can't parse the package.

Can you send me the signed APK, please. It should be in /sdcard/AEE/ (after using "Resign only" option).
Thank You.

**Comment by linsui** [comment]
I have send it to you. See above.

**Comment by apk-editor** [comment]
> I'm using Android 11. The resigned apk can't be parsed.
> [com.cosmos.unreddit_aee-signed.apk.zip](https://github.com/apk-editor/APK-Explorer-Editor/files/6960753/com.cosmos.unreddit_aee-signed.apk.zip)

It is ready funny, but this attached version installed fine on Android 10. Anyway, I'll try reproduce this issue on Android 11 emulator later. Thanks.

**Comment by apk-editor** [comment]
@linsui 
Okay, I found this issue specific to certain apks (the attached one and likely, many others). Currently I have no clue. So,  **bug** and **help wanted** labels are added. Also, I'll keep this issue open until I find a solution.

**Comment by linsui** [comment]
Thanks!

**Comment by apk-editor** [comment]
@linsui 
This issue might be fixed (at least partially) as of [v0.25](https://github.com/apk-editor/APK-Explorer-Editor/releases/tag/v0.25). So, closing this issue. Feel free to open it, if you think the issue still exist.
